### ISSUE TITLE
Adding a spotlight page

### ISSUE THREAD

**Issue by aarondonwilliams** [pulsar-neighborhood/pulsar-neighborhood.github.io#61]
Would it be possible to add a spotlight page? With the idea being that we can show everyone who has submitted their image..

Also on this page would be a link to add "yourself to the spotlight".  If you click on an image, it would take you to the main page for the person.  Much the same way that if you click on the picture on the first page. 

Maybe turn it on when we get 10-20 people

**Comment by ddieruf** [comment]
Done
